### ISSUE TITLE
Support for USB760 - CDMA 3G modem by Verizon/NovatelSmithmicro

### ISSUE THREAD

**Issue by dejannenov** [Trixarian/sakis3g-source#7]
Hello,

I would like to inquire if sakis3g supports the Verizon USB760 modem, made by novatelwireless.

lsusb retuens:

Bus 001 Device 007: ID 1410:5030 Novatel Wireless

The i386 platform drivers I found in a .deb were written by smithmicro.

Thank you,

DN

**Comment by Trixarian** [comment]
It should be: `1410:5030:# Novatel U760`
